firebase:
  type: "service_account"
  auth_uri: "https://accounts.google.com/o/oauth2/auth"
  token_uri: "https://oauth2.googleapis.com/token"
  auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"

  project_id: '<need to implement key>'
  private_key_id: '<need to implement key>'
  private_key: >
    -----BEGIN PRIVATE KEY-----
    Need implement KEY!
    -----END PRIVATE KEY-----

  client_email: '<need to implement key>'
  client_id: '<need to implement key>'
  client_x509_cert_url: '<need to implement key>'
